config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
  validates :user_id, presence: true


end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles
  before_save {self.email = email.downcase}
  validates :username, presence: true,
             uniqueness: { case_sensitive: false },
             length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 },
             uniqueness: { case_sensitive: false },
             format: { with: VALID_EMAIL_REGEX }
  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?
def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end
def logged_in?
  !!current_user
end
def require_user
  if !logged_in?
  flash[:danger] = "You must be logged in to perform that action"
  redirect_to root_path
  end
end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "The article was successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      flash[:notice] = "The article was successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    flash[:notice] = "Article was successfully deleted"
    redirect_to articles_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :description)
    end



end

app/controllers/concerns/pages_controller.rb
class PagesController < ApplicationController

  def home
  end
  
  def about
  end
 
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "There was something wrong with your login information"
      render 'new'
    end

  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to To-do list #{@user.username}"

      redirect_to login_path
    else
      render 'new'
    end
  end

  def index
    #added
  end

  def show
    #added
    @user = current_user
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
<h2>The following errors prevent the list item to be created</h2>
<ul>
  <% @article.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_for @article do |f| %>
  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit :create %>
  </p>

<% end %>

<%= link_to "Back to Your To-do list", articles_path %>

app/views/articles/edit.html.erb
<h1>Editing existing article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Your To-do List</h1>
<p>
  <%= link_to "Create new list item", new_article_path %>
</p>
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
  </tr>
  <% @articles.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.description %></td>
    <td><%= link_to "Edit", edit_article_path(article) %></td>
    <td><%= link_to "Show", article_path(article) %></td>
    <td><%= link_to "Delete", article_path(article), method: :delete, data:{confirm: "Are you sure?"} %></td>
  </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>Create an article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h1>Showing selected list item</h1>

<p>Title: <%= @article.title %></p>
<p>Description: <%= @article.description %></p>
<%= link_to "Edit this item", edit_article_path(@article) %>
<%= link_to "Back to your To-do list", user_path(current_user) %>

app/views/layouts/_messages.html.erb
 <% flash.each do |name,msg| %>
    <ul>
      <li><%= msg %></li>
    </ul>
 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BetaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

 <%= render 'layouts/messages' %>
<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<h1>about page</h1>
<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<h1>To-do List</h1>
<%= link_to 'Log in', login_path %>|<%= link_to 'Sign up now', signup_path %>

app/views/users/index.html.erb
<h1>my to do list</h1>

app/views/users/new.html.erb
<h1>Sign up to To-do List</h1>
<% if @user.errors.any? %>
<h2>The following errors prevent the list item to be created</h2>
<ul>
  <% @user.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_for @user do |f| %>
  <p>
    <%= f.label :username %><br/>
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email %><br/>
    <%= f.email_field :email %>
  </p>
  <p>
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.submit "Sign up" %>
  </p>

<% end %>

<%= link_to "Back to home", root_path %>

app/views/users/show.html.erb
<h2><%= @user.username %></h2>
 <%= link_to "Create new list item", new_article_path %>
<table>
  <tr>
    <th>Title</th>
    <th>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</th>
    <th>Description</th>
  </tr>
  <% @user.articles.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</td>
    <td><%= article.description %></td>
    <td>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</td>
    <td><%= link_to "Edit", edit_article_path(article) %></td>
    <td><%= link_to "Show", article_path(article) %></td>
    <td><%= link_to "Done", article_path(article), method: :delete, data:{confirm: "Are you sure?"} %></td>
  </tr>
  <% end %>
</table>
<%= link_to 'Log out', logout_path, method: :delete%>